config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("staytrade.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("providers/", include("staytrade.providers.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

staytrade/providers/urls.py
from django.urls import path
from staytrade.providers.views.hotels import (
    HotelCreationWizard,
    HotelDetailView,
    HotelDeleteView,
    HotelUpdateView,
    MyHotelsListView,
)
from staytrade.providers.views.room_types import (
    RoomTypeCreationWizardView,
    RoomTypeDeleteView,
    RoomTypeDetailView,
    RoomTypeUpdateView,
    MyHotelRoomsListView,
)
from staytrade.providers.views.misc import (
    MyAreaView,
    HotelManagementView,
)
from staytrade.providers.views.meal_plans import (
    MealPlanListView,
    MealPlanCreateView,
    MealPlanDetailView,
    MealPlanUpdateView,
    MealPlanDeleteView,
    RoomTypeMealPlanPriceView,
)

app_name = "providers"
urlpatterns = [
    # Main area
    path("my_area/", MyAreaView.as_view(), name="my_area"),
    # Hotels
    path("my_hotels/", MyHotelsListView.as_view(), name="my_hotels_list"),
    path(
        "hotels/new/",
        HotelCreationWizard.as_view(),
        name="hotel_create_wizard_default",
    ),
    path(
        "hotels/new/<str:step>/",
        HotelCreationWizard.as_view(),
        name="hotel_create_wizard",
    ),
    path(
        "hotels/management/<int:pk>/",
        HotelManagementView.as_view(),
        name="hotel_management",
    ),
    path("hotels/<int:pk>/", HotelDetailView.as_view(), name="hotel_detail"),
    path("hotels/delete/<int:pk>/", HotelDeleteView.as_view(), name="hotel_delete"),
    path("hotels/update/<int:pk>/", HotelUpdateView.as_view(), name="hotel_update"),
    # Room types
    path(
        "roomtypes/new/<int:hotel_id>/",
        RoomTypeCreationWizardView.as_view(),
        name="room_type_create_wizard_default",
    ),
    path(
        "roomtypes/new/<int:hotel_id>/<str:step>/",
        RoomTypeCreationWizardView.as_view(),
        name="room_type_create_wizard",
    ),
    path(
        "my_rooms/<int:hotel_id>/",
        MyHotelRoomsListView.as_view(),
        name="my_hotel_rooms_list",
    ),
    path("roomtypes/<int:pk>/", RoomTypeDetailView.as_view(), name="roomtype_detail"),
    path(
        "roomtypes/delete/<int:pk>/",
        RoomTypeDeleteView.as_view(),
        name="roomtype_delete",
    ),
    path(
        "roomtypes/update/<int:pk>/",
        RoomTypeUpdateView.as_view(),
        name="roomtype_update",
    ),
    # Meal plans
    path(
        "mealplan/list/<int:hotel_id>/",
        MealPlanListView.as_view(),
        name="meal_plan_list",
    ),
    path(
        "mealplan/create/<int:hotel_id>/",
        MealPlanCreateView.as_view(),
        name="meal_plan_create",
    ),
    path(
        "mealplan/detail/<int:pk>/",
        MealPlanDetailView.as_view(),
        name="meal_plan_detail",
    ),
    path(
        "mealplan/update/<int:pk>/",
        MealPlanUpdateView.as_view(),
        name="meal_plan_update",
    ),
    path(
        "mealplan/delete/<int:pk>/",
        MealPlanDeleteView.as_view(),
        name="meal_plan_delete",
    ),
    # Meal plan room type  calendar
    path(
        "mealplan/prices/<int:hotel_id>",
        RoomTypeMealPlanPriceView.as_view(),
        name="room_type_meal_plan_price_offer",
    ),
]

staytrade/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

staytrade/providers/api/views.py
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import status
from staytrade.providers.models import RoomTypeMealPlanPrice
from .serializers import CalendarEventSerializer, RoomTypeMealPlanPriceBulkSerializer


class RoomPriceViewSet(viewsets.ViewSet):
    """
    ViewSet para gestionar los precios de las habitaciones
    """

    def create(self, request):
        """
        Endpoint POST /api/room-prices/
        Guarda un nuevo precio
        """
        serializer = RoomTypeMealPlanPriceBulkSerializer(data=request.data)
        if serializer.is_valid():
            RoomTypeMealPlanPrice.objects.create_or_update_prices(
                **serializer.validated_data
            )
            return Response(
                {"message": "Precio guardado"}, status=status.HTTP_201_CREATED
            )
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    @action(detail=False, methods=["get"])
    def calendar_data(self, request):
        """
        Endpoint GET /api/room-prices/calendar_data/
        Retorna los datos formateados para el calendario
        """
        room_type_id = request.query_params.get("room_type_id")
        meal_plan_id = request.query_params.get("meal_plan_id")
        start_date = request.query_params.get("start")
        end_date = request.query_params.get("end")

        if not all([room_type_id, meal_plan_id, start_date, end_date]):
            return Response([])

        prices = RoomTypeMealPlanPrice.objects.filter(
            room_type_id=room_type_id,
            meal_plan_id=meal_plan_id,
            start_date__gte=start_date,
            end_date__lte=end_date,
        )

        serializer = CalendarEventSerializer(prices, many=True)
        return Response(serializer.data)

staytrade/providers/views/hotels.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from django.shortcuts import redirect
from django.views.generic import (
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)
from formtools.wizard.views import SessionWizardView

from staytrade.providers.forms import (
    HotelBasicInfoForm,
    HotelLocationForm,
    HotelImagesForm,
)
from staytrade.providers.models import Hotel
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _


class HotelDetailView(LoginRequiredMixin, DetailView):
    model = Hotel
    template_name = "providers/hotel_detail.html"
    context_object_name = "hotel"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.object.name
        return context

    # Protects form outter users to view details.
    def get_queryset(self):
        return self.model.objects.filter(created_by=self.request.user)


class MyHotelsListView(LoginRequiredMixin, ListView):
    model = Hotel
    template_name = "providers/hotels_list.html"
    context_object_name = "hotels"
    paginate_by = 10

    def get_queryset(self):
        return self.model.objects.filter(created_by=self.request.user).order_by("name")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("Hotel list.")
        return context


class HotelCreationWizard(LoginRequiredMixin, SessionWizardView):
    form_list = [
        ("0", HotelBasicInfoForm),
        ("1", HotelLocationForm),
        ("2", HotelImagesForm),
    ]

    template_name = "providers/wizards/hotel_wizard_form.html"
    file_storage = FileSystemStorage()

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form=form, **kwargs)
        context["step_titles"] = {
            "0": _("Basic info"),
            "1": _("Location"),
            "2": _("Images"),
        }
        return context

    def get_step_url(self, step):
        """Genera la URL correcta del paso"""
        return reverse("hotel_create_wizard", kwargs={"step": step})

    def done(self, form_list, form_dict, **kwargs):
        hotel_data = {}
        for form in form_list:
            hotel_data.update(form.cleaned_data)

        valid_fields = [f.name for f in Hotel._meta.fields]
        filtered_data = {k: v for k, v in hotel_data.items() if k in valid_fields}

        if self.request.user.enterprise_account:
            filtered_data.update({"account": self.request.user.enterprise_account})

        hotel = Hotel.objects.create(**filtered_data, created_by=self.request.user)
        messages.info(self.request, _("Hotel created succsefully."))

        redirect_url = reverse("providers:hotel_detail", kwargs={"pk": hotel.pk})

        if self.request.headers.get("HX-Request"):
            response = HttpResponse()
            response["HX-Redirect"] = redirect_url
            return response

        return redirect(redirect_url)

    def render_next_step(self, form, **kwargs):
        """Renderiza solo el contenido del formulario si es una solicitud HTMX"""
        if self.request.headers.get("HX-Request"):
            # Cambiar el template para peticiones HTMX
            self.template_name = "providers/wizards/partials/hotel_wizard_form.html"
        response = super().render_next_step(form, **kwargs)
        return response

    def render(self, form=None, **kwargs):
        """Maneja el template correcto para peticiones HTMX"""
        if self.request.headers.get("HX-Request"):
            self.template_name = "providers/wizards/partials/hotel_wizard_form.html"
        return super().render(form, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        """Asigna un paso por defecto si no se recibe en la URL"""
        if "step" not in kwargs:
            return redirect(
                reverse("providers:hotel_create_wizard", kwargs={"step": "1"})
            )
        return super().dispatch(request, *args, **kwargs)


class HotelUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Hotel
    template_name = "providers/hotel_update_form.html"
    fields = [
        "name",
        "stars",
        "description",
        "main_picture",
        "second_picture",
        "third_picture",
        "site_url",
        "google_maps_location",
        "contact_phone",
        "text_location",
    ]
    success_message = _("Hotel successfully updated.")

    def get_success_url(self):
        return reverse_lazy("providers:hotel_detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"Modificar {self.object.name}"
        return context


class HotelDeleteView(LoginRequiredMixin, DeleteView):
    model = Hotel
    success_url = reverse_lazy("providers:my_hotels_list")

staytrade/providers/views/meal_plans.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    TemplateView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.http import HttpResponse
from staytrade.providers.models import MealPlan, RoomType
from .mixins import HotelContextMixin


class MealPlanListView(LoginRequiredMixin, HotelContextMixin, ListView):
    model = MealPlan
    template_name = "providers/meal_plans/list.html"
    context_object_name = "meal_plans"
    paginate_by = 10

    def get_queryset(self):
        return self.model.objects.filter(hotel=self.get_hotel_id()).order_by("name")


class MealPlanCreateView(
    LoginRequiredMixin, SuccessMessageMixin, HotelContextMixin, CreateView
):
    model = MealPlan
    template_name = "providers/meal_plans/form.html"
    fields = ["name", "details"]
    success_message = _("Meal plan successfully created.")

    def form_valid(self, form):
        form.instance.hotel_id = self.get_hotel_id()
        return super().form_valid(form)


class MealPlanUpdateView(
    LoginRequiredMixin, SuccessMessageMixin, HotelContextMixin, UpdateView
):
    model = MealPlan
    template_name = "providers/meal_plans/form.html"
    fields = ["name", "details"]
    success_message = _("Plan de comidas actualizado exitosamente.")


class MealPlanDetailView(LoginRequiredMixin, HotelContextMixin, DetailView):
    model = MealPlan
    template_name = "providers/meal_plans/detail.html"
    context_object_name = "meal_plan"


class MealPlanDeleteView(LoginRequiredMixin, HotelContextMixin, DeleteView):
    model = MealPlan
    template_name = "providers/meal_plans/confirm_delete.html"

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        if request.headers.get("HX-Request"):
            response = HttpResponse()
            response["HX-Redirect"] = self.get_success_url()
        return response


class RoomTypeMealPlanPriceView(LoginRequiredMixin, HotelContextMixin, TemplateView):
    # Template management is done using an API to implenet it with full-calendar
    template_name = "providers/room_type_meal_plan/price_calendar.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        hotel_id = self.get_hotel_id()

        context.update(
            {
                "room_types": RoomType.objects.filter(hotel_id=hotel_id),
                "meal_plans": MealPlan.objects.filter(hotel_id=hotel_id),
                "title": _("Manage price offer"),
            }
        )
        return context

staytrade/providers/views/misc.py
from django.views.generic import TemplateView
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin


# Main area
class MyAreaView(LoginRequiredMixin, TemplateView):
    template_name = "providers/providers_area.html"

    def render_to_response(self, context, **response_kwargs):
        if self.request.headers.get("HX-Request"):
            response = HttpResponse()
            # Redirigir a una URL específica en lugar de renderizar el template
            response["HX-Redirect"] = self.request.build_absolute_uri(
                reverse("providers:my_area")
            )
            return response
        return super().render_to_response(context, **response_kwargs)


class HotelManagementView(LoginRequiredMixin, TemplateView):
    template_name = "providers/hotel_management_area.html"

    def render_to_response(self, context, **response_kwargs):
        if self.request.headers.get("HX-Request"):
            response = HttpResponse()
            # Redirigir a una URL específica en lugar de renderizar el template
            response["HX-Redirect"] = self.request.build_absolute_uri(
                reverse("providers:hotel_management")
            )
            return response
        return super().render_to_response(context, **response_kwargs)

staytrade/reservations/views.py
from django.shortcuts import render

# Create your views here.

staytrade/templates/providers/hotel_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="content">
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between align-items-center mb-3">
                  <div>
                      <h1 class="h3 mb-0">{{ hotel.name }}</h1>
                    <div class="hotel-stars">
                        {% for i in "12345" %}
                            {% if forloop.counter <= hotel.stars %}
                                <i class="fas fa-star text-warning"></i>
                            {% else %}
                                <i class="far fa-star text-warning"></i>
                            {% endif %}
                        {% endfor %}
                    </div>
                  </div>
                 <div class="action-buttons">
    <a href="{% url 'providers:hotel_update' hotel.id %}" class="btn btn-warning">
        <i class="fas fa-edit"></i> {% translate "Edit Hotel" %}
    </a>
    <a href="{% url 'providers:my_hotel_rooms_list' hotel_id=hotel.id %}" class="btn btn-primary">
        <i class="fas fa-add"></i> {% translate "Manage rooms" %}
    </a>
    <button class="btn btn-danger"
            data-bs-toggle="modal"
            data-bs-target="#deleteHotelModal">
        <i class="fas fa-trash"></i> {% translate "Delete Hotel" %}
    </button>
</div>
            </div>
            </div>
        </div>

        <div class="card-body">
            <!-- Galería de imágenes -->
            <div class="hotel-gallery mb-4">
                <div class="gallery-main">
                    {% if hotel.main_picture %}
                        <img src="{{ hotel.main_picture.url }}"
                             alt="{{ hotel.name }}"
                             class="main-image">
                    {% endif %}
                </div>
                <div class="gallery-thumbs">
                    {% if hotel.second_picture %}
                        <img src="{{ hotel.second_picture.url }}"
                             alt="{{ hotel.name }}"
                             class="thumb-image">
                    {% endif %}
                    {% if hotel.third_picture %}
                        <img src="{{ hotel.third_picture.url }}"
                             alt="{{ hotel.name }}"
                             class="thumb-image">
                    {% endif %}
                </div>
            </div>

            <!-- Información del hotel -->
            <div class="hotel-info">
                <div class="row">
                    <div class="col-md-8">
                        <div class="info-section">
                            <h2 class="h4">{% translate "Description" %}</h2>
                            <p>{{ hotel.description }}</p>
                        </div>
                    </div>
                    <div class="col-md-4">
<div class="contact-card">
    <h3 class="h5 mb-4">{% translate "Contact Information" %}</h3>
    <div class="contact-info-list">
        {% if hotel.site_url %}
        <div class="contact-item">
            <div class="contact-icon">
                <i class="fas fa-globe"></i>
            </div>
            <div class="contact-details">
                <span class="contact-label">{% translate "Website" %}</span>
                <a href="{{ hotel.site_url }}"
                   class="contact-value"
                   target="_blank">
                    {% translate "Visit website" %}
                </a>
            </div>
        </div>
        {% endif %}

        {% if hotel.text_location %}
        <div class="contact-item">
            <div class="contact-icon">
                <i class="fas fa-map-marker-alt"></i>
            </div>
            <div class="contact-details">
                <span class="contact-label">{% translate "Location" %}</span>
                <a href="{{ hotel.google_maps_location }}"
                   class="contact-value"
                   target="_blank">
                    {{ hotel.text_location }}
                </a>
            </div>
        </div>
        {% endif %}

        {% if hotel.contact_phone %}
        <div class="contact-item">
            <div class="contact-icon">
                <i class="fas fa-phone"></i>
            </div>
            <div class="contact-details">
                <span class="contact-label">{% translate "Contact phone" %}</span>
                <span class="contact-value">{{ hotel.contact_phone }}</span>
            </div>
        </div>
        {% endif %}
    </div>
</div>

                </div>
            </div>

            <div class="metadata">
                <small class="text-muted">
                    {% translate "Created by" %}: {{ hotel.created_by.name|default:hotel.created_by.username }}
                    <br>
                    {% translate "Creation date" %}: {{ hotel.created_at|date:"d/m/Y H:i" }}
                </small>
            </div>
        </div>
    </div>
</div>

<!-- Modal para confirmar eliminación -->
<div class="modal fade" id="deleteHotelModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{% translate "Confirm Deletion" %}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <p>{% translate "Are you sure you want to delete this hotel? This action cannot be undone." %}</p>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    {% translate "Cancel" %}
                </button>
                <form method="post" action="{% url 'providers:hotel_delete' hotel.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">
                        {% translate "Delete Hotel" %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

staytrade/templates/providers/hotel_management_area.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="content">
    <h1 class="mb-4">Hotel: {{ pk }}</h1>
    <div class="provider-areas">
        <!-- Área de Tipos de Habitación -->
        <a href="{% url 'providers:my_hotel_rooms_list' hotel_id=pk %}" class="provider-area-card">
            <div class="provider-area-content">
                <span class="fa-stack fa-2x mb-3">
                    <i class="fas fa-square fa-stack-2x text-primary"></i>
                    <i class="fas fa-door-open fa-stack-1x text-white"></i>
                </span>
                <h2>{% translate "Room types" %}</h2>
                <p>{% translate "Define and manage your room types offer." %}</p>
            </div>
        </a>

        <!-- Área de Tipos de Pensión -->
        <a href="{% url 'providers:meal_plan_list' hotel_id=pk  %}" class="provider-area-card">
            <div class="provider-area-content">
                <span class="fa-stack fa-2x mb-3">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-utensils fa-stack-1x text-white"></i>
                </span>
                <h2>{% translate "Meal types" %}</h2>
                <p>{% translate "Define your meal plans" %}</p>
            </div>
        </a>
        <!-- Área de precios -->
        <a href="{% url 'providers:room_type_meal_plan_price_offer' hotel_id=pk %}" class="provider-area-card">
            <div class="provider-area-content">
                <span class="fa-stack fa-2x mb-3">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-coins fa-stack-1x text-white"></i>
                </span>
                <h2>{% translate "Plan Prices" %}</h2>
                <p>{% translate "Define prices for each room and meal plan" %}</p>
            </div>
        </a>
    </div>
</div>
{% endblock content %}

staytrade/templates/providers/roomtypes_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
<div class="container py-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2>{% trans "Tipos de Habitaciones" %}</h2>
        {% if hotel_id %}
        <a href="{% url 'providers:room_type_create_wizard' hotel_id=hotel_id step=0 %}"
           class="btn btn-primary">
            <i class="fas fa-plus"></i> {% trans "Agregar Tipo de Habitación" %}
        </a>
        {% endif %}
    </div>

    <div class="row">
        {% for room_type in object_list %}
        <div class="col-md-6 col-lg-4 mb-4">
            <div class="card h-100">
                {% if room_type.main_picture %}
                    <img src="{{ room_type.main_picture.url }}"
                         class="card-img-top"
                         alt="{{ room_type.name }}"
                         style="height: 200px; object-fit: cover;">
                {% else %}
                    <div class="card-img-top bg-light d-flex align-items-center justify-content-center"
                         style="height: 200px;">
                        <i class="fas fa-bed fa-3x text-secondary"></i>
                    </div>
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ room_type.name }}</h5>

                    <div class="room-info mb-3">
                        <div class="d-flex justify-content-between mb-2">
                            <span>
                                <i class="fas fa-user"></i> {{ room_type.adults_capacity }}
                                <i class="fas fa-child ms-2"></i> {{ room_type.children_capacity }}
                            </span>
                            <span>
                                <i class="fas fa-door-closed"></i> {{ room_type.stock }}
                            </span>
                        </div>

                        <div class="status-badge">
                            {% if room_type.is_available %}
                                <span class="badge bg-success">
                                    <i class="fas fa-check"></i> {% trans "Disponible" %}
                                </span>
                            {% else %}
                                <span class="badge bg-danger">
                                    <i class="fas fa-times"></i> {% trans "No Disponible" %}
                                </span>
                            {% endif %}
                        </div>
                    </div>

                    <p class="card-text text-muted">
                        {{ room_type.description|truncatewords:20 }}
                    </p>
                </div>

                <div class="card-footer bg-transparent border-top-0">
                    <div class="d-flex justify-content-between">
                        <a href="{% url 'providers:roomtype_detail' room_type.id %}"
                           class="btn btn-outline-primary btn-sm">
                            <i class="fas fa-eye"></i> {% trans "Ver Detalles" %}
                        </a>
                        <a href="{% url 'providers:roomtype_update' room_type.id %}"
                           class="btn btn-outline-secondary btn-sm">
                            <i class="fas fa-edit"></i> {% trans "Editar" %}
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-12">
            <div class="alert alert-info text-center">
                <i class="fas fa-info-circle me-2"></i>
                {% trans "No hay tipos de habitaciones registrados." %}
            </div>
        </div>
        {% endfor %}
    </div>

    {% if is_paginated %}
    <nav aria-label="{% trans 'Navegación de páginas' %}" class="mt-4">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <i class="fas fa-chevron-left"></i>
                </a>
            </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active">
                        <span class="page-link">{{ num }}</span>
                    </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <i class="fas fa-chevron-right"></i>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

{% block extra_css %}
<style>
    .card {
        transition: transform 0.2s;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 4px 8px rgba(0,0,0,0.2);
    }

    .room-info {
        font-size: 0.9rem;
    }

    .status-badge {
        text-align: right;
    }

    .card-footer {
        padding-top: 1rem;
    }

    .btn-sm {
        padding: 0.25rem 0.5rem;
        font-size: 0.875rem;
    }
</style>
{% endblock %}